name: mysql84-phpmyadmin-nginx-path-proxy

services:
  nginx_path_proxy:
    image: nginx:alpine
    container_name: phpmyadmin-nginx-path-proxy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/path-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mysql84_network

networks:
  mysql84_network:
    external: true
    name: mysql84_network
