name: mysql84-phpmyadmin-apache-path-proxy

services:
  apache_path_proxy:
    image: httpd:2.4-alpine
    container_name: phpmyadmin-apache-path-proxy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./apache-proxy/httpd-path.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - mysql84_network

networks:
  mysql84_network:
    external: true
    name: mysql84_network
